name: Deploy Production

on: workflow_dispatch

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 15
      - run: mvn clean install
  deploy-to-heroku:
    name: Heroku
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v2
      - run: sed -ri 's/codecoach-dev/codecoach/g' ./application/src/main/resources/application.properties
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "codecoach-marvel"
          heroku_email: "willekens.rafael@gmail.com"
